blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions and Help
    url: https://github.com/react-native-elements/react-native-elements/discussions/new
    about: Want to ask something? Create new Discussion.
  - name: âš›ï¸ React Native Issues
    url: https://github.com/facebook/react-native/issues
    about: Please report bugs or issues in the React Native repository.
  - name: ğŸ˜„ Want to say Hi? Join Discord
    url: https://discord.com/invite/e9RBHjkKHa
    about: Looking for help with your app? Please refer to the React Native Element's discord server.
