blank_issues_enabled: false
contact_links:
  - name: âš›ï¸ React Native Issues
    url:  https://github.com/facebook/react-native/issues
    about: Please report bugs or issues in the React Native repository.
  - name: ğŸ¤” Questions and Help
    url: https://react-native-elements-slack.herokuapp.com/
    about: Looking for help with your app? Please refer to the React Native Element's slack.
