name: (manual PR) Bump release version

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Release name
        required: true

jobs:
  publish:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Set env
        run: |
          BRANCH_NAME="bump-docs-$(date "+%Y%m%d%H%M%S")"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Bump docs version
        working-directory: website
        run: |
          yarn version ${{github.event.inputs.name}}

      - name: Bump base version
        working-directory: packages/base
        run: |
          npm version v${{github.event.inputs.name}}
      - name: Bump themed version
        working-directory: packages/themed
        run: |
          npm version v${{github.event.inputs.name}}

      - name: Config git
        run: |
          git config --local user.email "104670806+rneui@users.noreply.github.com"
          git config --local user.name "RNEUI"

      - name: Checkout
        run: |
          git add .
          git commit -m "Bump v${{github.event.inputs.pr}}"
          git checkout -b ${{ env.BRANCH_NAME }}
          git push --set-upstream origin ${{ env.BRANCH_NAME }} --force

      - name: Create Pull Request
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'chore: bump v${{github.event.inputs.pr}}',
              owner,
              repo,
              head: '${{ env.BRANCH_NAME }}',
              base: 'next',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr', 'need-review']
            });
