name: Bleeding Edge version
on:
  push:
    branches:
      - "next"
    paths-ignore:
      - "website/**"
      - "example/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-dist-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dist-
      - name: Install Dependencies
        run: yarn
      - run: yarn lint
      - run: yarn typescript
      - run: yarn test && npx codecov --disable=gcov
      - name: Build packages
        run: yarn build
      - name: Config git
        run: |
          git config --local user.email "react-native-elements-ci@users.noreply.github.com"
          git config --local user.name "React Native Elements CI"
      - name: Create local changes
        run: |
          sed -i -e 's/dist/src/g' .gitignore
          git add .
          git commit -m "Bleeding Edge Version" -a --no-verify
      - name: Deploy Bleeding Edge version'@react-native-elements/*' packages
        run: |
          for pkg in $(find ./packages -mindepth 1 -maxdepth 1 -type d -printf '%f\n'); do
               echo "Deploying @react-native-elements/$pkg"
               git push origin `git subtree split --prefix packages/$pkg -b $pkg`:refs/heads/$pkg --force
          done
