name: ci
on:
  pull_request:
    branches:
      - next
jobs:
  test:
    name: "check_unit_tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        run: |
          yarn
      - run: yarn test && npx codecov --disable=gcov
  typescript:
    name: "check_types"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        run: yarn
      - run: yarn typescript
  lint:
    name: "check_lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        run: yarn
      - run: yarn lint
      - run: yarn format
  docs-api:
    name: "check_docs_api"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Cache website dependencies
        uses: actions/cache@v2
        with:
          path: website/.yarn/cache
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - name: Install dependencies
        run: yarn install
      - name: Install website dependencies
        run: yarn install
        working-directory: website
      - name: Build ðŸ”§
        run: yarn docs-build-api
      - name: Check for API changes
        run: git diff --exit-code
