name: (manual) Upgrade expo SDK

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v2

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Set env
        run: |
          BRANCH_NAME="upgrade-expo-sdk-$(date "+%Y%m%d")"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: Upgrade Expo
        run: |
          cd example
          npm --global install expo-cli@latest
          npx expo upgrade --non-interactive
        continue-on-error: true
      - name: Config git
        run: |
          git config --local user.email "104670806+rneui@users.noreply.github.com"
          git config --local user.name "RNEUI"
      - name: Checkout
        continue-on-error: true
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git add .
          git commit -m "Upgrade Expo SDK"
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: '${{ env.BRANCH_NAME }}',
              base: 'next',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
